// General
export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const SET_PAGE = 'SET_PAGE';
export const SET_TOTAL = 'SET_TOTAL';
export const SET_CURRENT_PAGE_DATA = 'SET_CURRENT_PAGE_DATA';
export const SORT_ASC = 'SORT_ASC';
export const SORT_DESC = 'SORT_DESC';
export const REMOVE_FROM_CURRENT_PAGE_DATA = 'REMOVE_FROM_CURRENT_PAGE_DATA';
export const UPDATE_CURRENT_LOADED_DATA = 'CURRENT_LOADED_DATA';

// Auth
export const LOGIN_ERROR_MESSAGE = 'LOGIN_ERROR_MESSAGE';
export const REGISTER_ERRORS = 'REGISTER_ERRORS';
export const REGISTER_ERROR_MESSAGE = 'REGISTER_ERROR_MESSAGE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const USER_LOADED = 'USER_LOADED';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// System
export const GET_LOGS = 'GET_LOGS';
export const GET_CONTACTS = 'GET_CONTACTS';
export const SET_LOGIN_MODAL = 'SET_LOGIN_MODAL';

// Ingredients
export const GET_INGREDIENTS = 'GET_INGREDIENTS';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_ALLERGIES = 'GET_ALLERGIES';
export const CREATE_INGREDIENT = 'CREATE_INGREDIENT';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const CREATE_ALLERGY = 'CREATE_ALLERGY';
export const UPDATE_INGREDIENT = 'UPDATE_INGREDIENT';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const UPDATE_ALLERGY = 'UPDATE_ALLERGY';
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const DELETE_ALLERGY = 'DELETE_ALLERGY';

// Recipes
export const GET_RECIPES = 'GET_RECIPES';
export const GET_TOP_RECIPES = 'GET_TOP_RECIPES';
export const GET_RECIPE_CATEGORIES = 'GET_RECIPE_CATEGORIES';
export const GET_CUISINES = 'GET_CUISINES';
export const GET_RECIPE_TYPES = 'GET_RECIPE_TYPES';
export const GET_REVIEWS = 'GET_REVIEWS';
export const CREATE_RECIPE = 'CREATE_RECIPE';
export const CREATE_RECIPE_CATEGORY = 'CREATE_RECIPE_CATEGORY';
export const CREATE_CUISINE = 'CREATE_CUISINE';
export const CREATE_RECIPE_TYPE = 'CREATE_RECIPE_TYPE';
export const CREATE_REVIEW = 'CREATE_REVIEW';
export const UPDATE_RECIPE = 'UPDATE_RECIPE';
export const UPDATE_RECIPE_VIEW_COUNT = 'UPDATE_RECIPE_VIEW_COUNT';
export const UPDATE_RECIPE_CATEGORY = 'UPDATE_RECIPE_CATEGORY';
export const UPDATE_CUISINE = 'UPDATE_CUISINE';
export const UPDATE_RECIPE_TYPE = 'UPDATE_RECIPE_TYPE';
export const DELETE_RECIPE = 'DELETE_RECIPE';
export const DELETE_RECIPE_CATEGORY = 'DELETE_RECIPE_CATEGORY';
export const DELETE_CUISINE = 'DELETE_CUISINE';
export const DELETE_RECIPE_TYPE = 'DELETE_RECIPE_TYPE';
export const DELETE_REVIEW = 'DELETE_REVIEW';
export const UNSAVE_RECIPE = 'UNSAVE_RECIPE';
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const SET_CUSTOMISING = 'SET_CUSTOMISING';
export const SET_SORT = 'SET_SORT';
export const CLEAR_CUSTOMISING = 'CLEAR_CUSTOMISING';
export const CLEAR_REVIEWS = 'CLEAR_REVIEWS';
export const SORT_BY_RATING = 'rating';
export const SORT_BY_VIEWS = 'views';
export const SET_SUCCESS = 'SET_SUCCESS';

// Filters
export const SET_FILTERS = 'SET_FITLERS';
export const ADD_FILTER = 'ADD_FILTER';
export const REMOVE_FILTER = 'REMOVE_FILTER';
export const RESET_FILTERS = 'RESET_FILTERS';
export const SET_AVAILABLE_INGREDIENTS = 'SET_AVAILABLE_INGREDIENTS';
export const SET_AVAILABLE_CUISINE = 'SET_AVAILABLE_CUISINE';
export const SET_AVAILABLE_RECIPE_TYPES = 'SET_AVAILABLE_RECIPE_TYPES';
export const SET_AVAILABLE_ALLERGIES = 'SET_AVAILABLE_ALLERGIES';
export const SET_AVAILABLE_DURATION = 'SET_AVAILABLE_DURATION';
export const INGREDIENT_FILTER = 'INGREDIENT_FILTER';
export const CUISINE_FILTER = 'CUISINE_FILTER';
export const RECIPE_TYPE_FILTER = 'RECIPE_TYPE_FILTER';
export const ALLERGIES_FILTER = 'ALLERGIES_FILTER';
export const DURATION_FILTER = 'DURATION_FILTER';
export const LESS_THAN = 'less than';
export const MORE_THAN = 'more than';

// Users
export const GET_USERS = 'GET_USERS';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_SAVED_RECIPES = 'GET_SAVED_RECIPES';
export const GET_CUSTOM_RECIPES = 'GET_CUSTOM_RECIPES';
export const GET_MY_RECIPES = 'GET_MY_RECIPES';
export const ADD_CUSTOM_RECIPE = 'ADD_CUSTOM_RECIPE';
export const ADD_MY_RECIPE = 'ADD_MY_RECIPE';
export const UPDATE_CUSTOM_RECIPE = 'UPDATE_CUSTOM_RECIPE';
export const UPDATE_MY_RECIPE = 'UPDATE_MY_RECIPE';
export const REMOVE_CUSTOM_RECIPE = 'REMOVE_CUSTOM_RECIPE';
export const REMOVE_MY_RECIPE = 'REMOVE_MY_RECIPE';
